
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WallPostByTechBrij.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UserProfile
{

    public UserProfile()
    {

        this.PostComments = new HashSet<PostComment>();

        this.Posts = new HashSet<Post>();

    }


    public int UserId { get; set; }

    public string UserName { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Address { get; set; }

    public string Country { get; set; }

    public string Email { get; set; }

    public string Gender { get; set; }

    public string Mobile { get; set; }



    public virtual ICollection<PostComment> PostComments { get; set; }

    public virtual ICollection<Post> Posts { get; set; }

}

}
